nav_docking_node:
  ros__parameters:
    pid_parameters:
      kp_x: 3.1   # proportional gain for x-direction
      ki_x: 0.0   # Integral gain
      kd_x: 0.01  # derivative gain

      kp_y: 5.1   # proportional gain for y-direction
      ki_y: 0.0   # Integral gain
      kd_y: 0.01  # Small derivative gain to handle sudden changes

      kp_z: 0.1   # proportional gain for angular control
      ki_z: 0.0   # Integral gain
      kd_z: 0.01  # derivative
